### ISSUE TITLE
[v1.3.1] Equalizer in Sample Editor is completely useless

### ISSUE THREAD

**Issue by PITmast** [polyend/TrackerBetaTesting#1040]
Hi

Do you guys notice anything after applying this effect?
For example after boost (+12dB) mid frequency.

Regards
Piotr 

* How often does this bug happen? (every time, often, "it only happened once")
every time

* Does this bug happen in previous firmware versions?
I do not know

* Does this bug happen in every project?
* Yes

**Comment by tfspsound** [comment]
Checkout the milestones for 1.4 this is on the list.

**Comment by thebradclay** [comment]
@tfspsound has it been fixed in the current beta?

**Comment by dirtysampling** [comment]
I confirm this. EQ  effect does not do anything.

**Comment by MortalJS** [comment]
Fixed in 1.4
Duplicate with #1174.

**Comment by trutypesounds** [comment]
@MortalJS its not fixed, eq still works not like eq guys, please make it the right way!
